# DataPreprocessing

In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import pandas as pd

In [3]:
data = pd.read_json('intents.json')

In [4]:
data.head()

                                             intents
0  [{'tag': 'job_seeker_greeting', 'patterns': ['...

In [5]:
data.shape

(1, 1)

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 1 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   intents  1 non-null      object
dtypes: object(1)
memory usage: 136.0+ bytes

In [7]:
df = data.dropna()

In [8]:
df.isnull().sum()

intents    0
dtype: int64

In [9]:
df.info

<bound method DataFrame.info of                                              intents
0  [{'tag': 'job_seeker_greeting', 'patterns': ['...>

In [10]:
df.columns

Index(['intents'], dtype='object')

In [11]:
df.size

1

In [12]:
df.describe()

                                                  intents
count                                                   1
unique                                                  1
top     [{'tag': 'job_seeker_greeting', 'patterns': ['...
freq                                                    1

In [13]:
df.head()

                                             intents
0  [{'tag': 'job_seeker_greeting', 'patterns': ['...

In [14]:
df.head()

                                             intents
0  [{'tag': 'job_seeker_greeting', 'patterns': ['...

In [15]:
import ydata_profiling as yp
import pandas_profiling
from pandas_profiling import ProfileReport
from ydata_profiling.model import describe
prof = ProfileReport(df)
prof.to_file(output_file='Report.html')

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]